ci/package_core: multi-artifact support
Add a new "board.build.artifact" option to boards.txt to specify which
artifact a board belongs to. If not specified, the board will
automatically be added to "zephyr_contrib".

The artifact names collected from boards.txt (plus the auto "zephyr"
package, which includes all boards) are used to build and package each
artifact in the GitHub Actions workflow; in particular, the FQBN of each
board will depend on its artifact's "architecture" field.
The test action is also updated to test each artifact on the appropriate
boards.

Individual package JSON files are in the extra/artifacts directory,
along with common include/exclude files for packaging.

Signed-off-by: Luca Burelli <l.burelli@arduino.cc>

diff --git a/.github/workflows/package_core.yml b/.github/workflows/package_core.yml
--- a/.github/workflows/package_core.yml
+++ b/.github/workflows/package_core.yml
@@ -7,7 +7,7 @@ on:
 jobs:
 
   package-core:
-    name: Build and package core
+    name: Build and package cores
     runs-on: ubuntu-latest
     env:
       CCACHE_IGNOREOPTIONS: -specs=*
@@ -15,6 +15,8 @@ jobs:
       CORE_TAG: ${{ env.CORE_TAG }}
       CORE_HASH: ${{ env.CORE_HASH }}
       ALL_BOARD_DATA: ${{ env.ALL_BOARD_DATA }}
+      ARTIFACTS: ${{ env.ARTIFACTS }}
+      SUB_ARCHES: ${{ env.SUB_ARCHES }}
     steps:
       - name: Install OS dependencies
         working-directory: /opt
@@ -54,32 +56,54 @@ jobs:
         run: |
           ./extra/build_all.sh -f
 
-      - name: Package core
+      - name: Package cores
         run: |
-          PACKAGE=zephyr
-          CORE_ARTIFACT=ArduinoCore-$PACKAGE-${CORE_HASH}
-          ./extra/package_core.sh ${CORE_TAG} distrib/${CORE_ARTIFACT}.tar.bz2
+          jq -cr '.[]' <<< ${ARTIFACTS} | while read -r artifact; do
+            ARTIFACT_NAME=ArduinoCore-${artifact}-${CORE_HASH}
+            ./extra/package_core.sh ${artifact} ${CORE_TAG} distrib/${ARTIFACT_NAME}.tar.bz2
+          done
 
-      - name: Archive core
+      - name: Archive cores
         uses: actions/upload-artifact@v4
         with:
-          name: ArduinoCore-zephyr-${{ env.CORE_HASH }}
+          name: ArduinoCore-archives-${{ env.CORE_HASH }}
           path: distrib/*.tar.bz2
 
+  split-core:
+    name: Split off ${{ matrix.artifact }}
+    runs-on: ubuntu-latest
+    needs: package-core
+    env:
+      ALL_CORES_ARTIFACT: ArduinoCore-archives-${{ needs.package-core.outputs.CORE_HASH }}
+      CORE_ARTIFACT: ArduinoCore-${{ matrix.artifact }}-${{ needs.package-core.outputs.CORE_HASH }}
+    strategy:
+      matrix:
+        artifact: ${{ fromJSON( needs.package-core.outputs.ARTIFACTS ) }}
+    steps:
+      - uses: actions/download-artifact@v4
+        with:
+          name: ${{ env.ALL_CORES_ARTIFACT }}
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.CORE_ARTIFACT }}
+          path: ${{ env.CORE_ARTIFACT }}.tar.bz2
+
   test-core:
-    name: Test on ${{ matrix.board }}
+    name: Test ${{ matrix.subarch }}:${{ matrix.board }}
     runs-on: ubuntu-latest
     needs:
       - package-core
+      - split-core
     strategy:
       matrix:
         include:
           ${{ fromJSON( needs.package-core.outputs.ALL_BOARD_DATA ) }}
       fail-fast: false
     env:
-      PLAT: arduino:zephyr
-      FQBN: arduino:zephyr:${{ matrix.board }}
-      CORE_ARTIFACT: ArduinoCore-zephyr-${{ needs.package-core.outputs.CORE_HASH }}
+      PLAT: arduino:${{ matrix.subarch }}
+      FQBN: arduino:${{ matrix.subarch }}:${{ matrix.board }}
+      CORE_ARTIFACT: ArduinoCore-${{ matrix.artifact }}-${{ needs.package-core.outputs.CORE_HASH }}
     steps:
       - uses: actions/download-artifact@v4
         with:
@@ -127,7 +151,7 @@ jobs:
               repo: context.repo.repo,
               run_id: context.runId
             });
-            const job_name = `Test on ${{ matrix.board }}`
+            const job_name = `Test ${{ matrix.subarch }}:${{ matrix.board }}`
             return workflow_run.jobs.find((job) => job.name === job_name).id;
 
       - name: Prepare log
@@ -159,37 +183,41 @@ jobs:
           merge-multiple: true
 
       - run: |
-          echo "### Core test results:" >> "$GITHUB_STEP_SUMMARY"
-          jq -c '.[]' <<< "$ALL_BOARD_DATA" | while read -r BOARD_DATA; do
-            BOARD=$(echo $BOARD_DATA | jq -cr '.board')
-            VARIANT=$(echo $BOARD_DATA | jq -cr '.variant')
-            FQBN="arduino:zephyr:$BOARD"
-            REPORT_FILE="$(echo $FQBN | tr ':' '-').json"
-            if [ ! -f $REPORT_FILE ]; then
-              echo "* :x: $BOARD (`$VARIANT`) - No report found?" >> "$GITHUB_STEP_SUMMARY"
-            else
-              REPORT=$(jq -cr '.boards[0].sketches[0]' $REPORT_FILE)
-              JOB_ID=$(echo $REPORT | jq -cr '.job_id')
-              JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${JOB_ID}#step:5:2"
-              if ! $(echo $REPORT | jq -cr '.compilation_success') ; then
-                echo "* :x: [$BOARD]($JOB_URL) (\`$VARIANT\`) - Build failed" >> "$GITHUB_STEP_SUMMARY"
+          ARTIFACTS=$(jq -cr 'map(.artifact) | unique | .[]' <<< ${ALL_BOARD_DATA}) # this avoids the 'zephyr' artifact
+          for artifact in $ARTIFACTS ; do
+            echo "### \`$artifact\` test results:" >> "$GITHUB_STEP_SUMMARY"
+            jq -c "map(select(.artifact == \"$artifact\")) | .[]" <<< ${ALL_BOARD_DATA} | while read -r BOARD_DATA; do
+              BOARD=$(echo $BOARD_DATA | jq -cr '.board')
+              VARIANT=$(echo $BOARD_DATA | jq -cr '.variant')
+              SUBARCH=$(echo $BOARD_DATA | jq -cr '.subarch')
+              FQBN="arduino:$SUBARCH:$BOARD"
+              REPORT_FILE="$(echo $FQBN | tr ':' '-').json"
+              if [ ! -f $REPORT_FILE ]; then
+                echo "* :x: $BOARD (\`$VARIANT\`) - No report found?" >> "$GITHUB_STEP_SUMMARY"
               else
-                WARNINGS=$(echo $REPORT | jq -cr '.warnings.current.absolute // 0')
-                if [ $WARNINGS -eq 0 ]; then
-                  echo "* :white_check_mark: $BOARD (\`$VARIANT\`) - Build successful" >> "$GITHUB_STEP_SUMMARY"
+                REPORT=$(jq -cr '.boards[0].sketches[0]' $REPORT_FILE)
+                JOB_ID=$(echo $REPORT | jq -cr '.job_id')
+                JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${JOB_ID}#step:5:2"
+                if ! $(echo $REPORT | jq -cr '.compilation_success') ; then
+                  echo "* :x: [$BOARD]($JOB_URL) (\`$VARIANT\`) - Build failed" >> "$GITHUB_STEP_SUMMARY"
                 else
-                  echo >> "$GITHUB_STEP_SUMMARY"
-                  echo "<details><summary>&nbsp;&nbsp; :warning: <a href=\"$JOB_URL\">$BOARD</a> (<tt>$VARIANT</tt>) - $WARNINGS warnings:</summary>" >> "$GITHUB_STEP_SUMMARY"
-                  echo >> "$GITHUB_STEP_SUMMARY"
-                  echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
-                  echo $REPORT | jq -cr '.warnings_log[]' >> "$GITHUB_STEP_SUMMARY"
-                  echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
-                  echo >> "$GITHUB_STEP_SUMMARY"
-                  echo "</details>" >> "$GITHUB_STEP_SUMMARY"
-                  echo >> "$GITHUB_STEP_SUMMARY"
+                  WARNINGS=$(echo $REPORT | jq -cr '.warnings.current.absolute // 0')
+                  if [ $WARNINGS -eq 0 ]; then
+                    echo "* :white_check_mark: $BOARD (\`$VARIANT\`) - Build successful" >> "$GITHUB_STEP_SUMMARY"
+                  else
+                    echo >> "$GITHUB_STEP_SUMMARY"
+                    echo "<details><summary>&nbsp;&nbsp; :warning: <a href=\"$JOB_URL\">$BOARD</a> (<tt>$VARIANT</tt>) - $WARNINGS warnings:</summary>" >> "$GITHUB_STEP_SUMMARY"
+                    echo >> "$GITHUB_STEP_SUMMARY"
+                    echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
+                    echo $REPORT | jq -cr '.warnings_log[]' >> "$GITHUB_STEP_SUMMARY"
+                    echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
+                    echo >> "$GITHUB_STEP_SUMMARY"
+                    echo "</details>" >> "$GITHUB_STEP_SUMMARY"
+                    echo >> "$GITHUB_STEP_SUMMARY"
+                  fi
                 fi
               fi
-            fi
+            done
           done
 
       - name: Clean up intermediate artifacts
@@ -220,11 +248,11 @@ jobs:
       id-token: write
       contents: read
     env:
-      CORE_ARTIFACT: ArduinoCore-zephyr-${{ needs.package-core.outputs.CORE_HASH }}
+      ALL_CORES_ARTIFACT: ArduinoCore-archives-${{ needs.package-core.outputs.CORE_HASH }}
     steps:
       - uses: actions/download-artifact@v4
         with:
-          name: ${{ env.CORE_ARTIFACT }}
+          name: ${{ env.ALL_CORES_ARTIFACT }}
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -236,37 +264,52 @@ jobs:
         run: aws s3 cp ArduinoCore-*.tar.bz2 s3://${{ secrets.S3_BUCKET }}/
 
   publish-json:
-    name: Publish json
+    name: Publish jsons
     runs-on: ubuntu-latest
     if: ${{ github.event_name == 'push' && github.repository == 'arduino/ArduinoCore-zephyr' }}
     needs:
       - package-core
       - test-core
     env:
-      CORE_ARTIFACT: ArduinoCore-zephyr-${{ needs.package-core.outputs.CORE_HASH }}
+      ALL_CORES_ARTIFACT: ArduinoCore-archives-${{ needs.package-core.outputs.CORE_HASH }}
       CORE_TAG: ${{ needs.package-core.outputs.CORE_TAG }}
+      CORE_HASH: ${{ needs.package-core.outputs.CORE_HASH }}
+      ARTIFACTS: ${{ needs.package-core.outputs.ARTIFACTS }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
           persist-credentials: false
-          sparse-checkout: |
-            extra/gen_package_index_json.sh
-            extra/zephyr-core-template.json
+          fetch-tags: true
 
       - uses: actions/download-artifact@v4
         with:
-          name: ${{ env.CORE_ARTIFACT }}
+          name: ${{ env.ALL_CORES_ARTIFACT }}
 
-      - name: Prepare package index snippet
+      - name: Prepare package index snippets
         run: |
-          PACKAGE=zephyr
-          ARTIFACT_FILE=ArduinoCore-${PACKAGE}-${CORE_HASH}.tar.bz2
-          PACKAGE_JSON=ArduinoCore-${PACKAGE}-${CORE_TAG}.json
-          ./extra/gen_package_index_json.sh ${CORE_TAG} ${ARTIFACT_FILE} > ${PACKAGE_JSON}
+          jq -cr '.[]' <<< ${ARTIFACTS} | while read -r artifact; do
+            ARTIFACT_FILE=ArduinoCore-${artifact}-${CORE_HASH}.tar.bz2
+            PACKAGE_JSON=ArduinoCore-${artifact}-${CORE_TAG}.json
+            ./extra/gen_package_index_json.sh ${artifact} ${ARTIFACT_FILE} ${PACKAGE_JSON}
+          done
 
-      - name: Archive package index snippet
+      - name: Archive package index snippets
         uses: actions/upload-artifact@v4
         with:
           name: ArduinoCore-zephyr-${{ env.CORE_TAG }}-jsons
           path: ArduinoCore-*-${{ env.CORE_TAG }}.json
+
+  cleanup-artifacts:
+    runs-on: ubuntu-latest
+    needs:
+      - package-core
+      - publish-core
+      - publish-json
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Clean up intermediate artifacts
+        uses: geekyeggo/delete-artifact@v5.1.0
+        with:
+          name: ArduinoCore-archives-${{ needs.package-core.outputs.CORE_HASH }}
+          failOnError: false
